FROM node:20.11.1

ARG TARGETPLATFORM
ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT
ARG BUILDPLATFORM
ARG BUILDOS
ARG BUILDARCH
ARG BUILDVARIANT

RUN echo "I'm building for TARGETPLATFORM : $TARGETPLATFORM"
RUN echo "I'm building for TARGETOS : $TARGETOS"
RUN echo "I'm building for TARGETARCH : $TARGETARCH"
RUN echo "I'm building for TARGETVARIANT : $TARGETVARIANT"
RUN echo "I'm building for BUILDPLATFORM : $BUILDPLATFORM"
RUN echo "I'm building for BUILDOS : $BUILDOS"
RUN echo "I'm building for BUILDARCH : $BUILDARCH"
RUN echo "I'm building for BUILDVARIANT : $BUILDVARIANT"