services:
  spt:
    image: spt/spt-server:3.8.1
    build:
      context: .
      # args:
      #   SPT_BRANCH: "3.8.1-DEV"
      #   SPT: "HEAD"
    container_name: spt
    volumes:
      - ./server_data:/opt/server_data
    ports:
      - "6969-6971:6969-6971"
    # environment:
    #   - LC_ALL=ko_kr.utf-8
    # restart: unless-stopped
