services:
  fika:
    image: spt/fika-server:v2.1.0
    build:
      context: .
      # args:
      #   SPT : 3.8.3
      #   SPT_COMMIT : HEAD
      #   FIKA : v2.1.0
      #   FIKA_COMMIT : HEAD
    volumes:
      - ./server_data:/opt/server_data
    # environment:
    #   - LC_ALL=ko_kr.utf-8
    ports:
      - "6969-6971:6969-6971"
      - "25565/udp"
    restart: unless-stopped
# networks:
#   default:
#     name: nginx_proxy
#     external: true
